### ISSUE TITLE
Proper command running in Python

### ISSUE THREAD

**Issue by Djent-** [noahpowers/nlzr#4]
https://github.com/noahpowers/nlzr/blob/4e3ce8eb1dfdee39f437a093796e23d96764073e/command-timeline.py#L8

These don't work from a Python script because these commands should take place in a bash interpreter (/bin/bash), and not in a general "command" kind of way. Try using `subprocess.Popen(["/bin/bash", "-i", "-c", "history -r; history"])` to display the current history file.

This will still not make bash environment variable exports persist, however. Those should be configured in .bashrc. The reason is because environment variables are per-process, and you can't modify another process' environment variables (i.e Python modifying your shell's environment variables).

**Comment by noahpowers** [comment]
Thanks for the feeback @Djent- It's something I tried and didn't have success with, so I just commented it so others can still see it. I'll look into revisiting it down the road. It's a bit rudimentary at the moment.

**Comment by noahpowers** [comment]
@Djent- If you're interested in this script, I wanted to let you know that @tarrell13 and I created a new repo (ref: https://github.com/noahpowers/CommandTimeline that will contain this script. The new repo will also be more robust and include other features, such as a DB for tracking the commands, and a future API for submitting one's commands into the DB.
